import { Injectable, signal, computed } from '@angular/core';

export type Langue = 'fr' | 'ar' | 'en';

@Injectable({ providedIn: 'root' })
export class LangueService {

  langue = signal<Langue>('fr');

  private traductions = {
    fr: {
      dashboard: 'Dashboard',
      tableauDeBord: 'Tableau de Bord',
      medicaments: 'Médicaments',
      fournisseurs: 'Fournisseurs',
      clients: 'Clients',
      ventes: 'Ventes',
      recherche: 'Recherche',
      rechercher: 'Rechercher',
      parametres: 'Paramètres',
      modeSombre: 'Mode sombre',
      modeClaire: 'Mode clair',
      deconnexion: 'Déconnexion',
      alertes: 'alerte(s) stock',
      alertesStock: 'Alertes Stock',
      expirentBientot: 'Expirent bientôt',
      chiffreAffaires: "Chiffre d'affaires",
      totalVentes: 'Total ventes',
      ventesAujourdhui: "Ventes aujourd'hui",
      actionsRapides: 'Actions rapides',
      nouveauMedicament: '💊 Nouveau médicament',
      nouvelleVente: 'Nouvelle vente',
      nouveauClient: '👥 Nouveau client',
      nouveauFournisseur: '🏭 Nouveau fournisseur',
      top3: 'Top 3 médicaments les plus vendus',
      vendus: 'vendus',
      dernieresVentes: 'Dernières ventes',
      mettreAJour: 'Mettre à jour',
      expireLe: 'Expire le',
      unitesRestantes: 'unités restantes',
      ajouter: 'Ajouter',
      stockMedicaments: 'Stock des Médicaments',
      gererInventaire: 'Gérez votre inventaire',
      nomReference: 'Nom, référence...',
      categorie: 'Catégorie',
      toutesCategories: 'Toutes les catégories',
      etatStock: 'État du Stock',
      tous: 'Tous',
      enAlerte: 'En alerte',
      prix: 'Prix',
      stock: 'Stock',
      expiration: 'Expiration',
      unites: 'unités',
      ordonnanceRequise: 'Ordonnance requise',
      voirDetails: 'Voir détails',
      modifier: 'Modifier',
      supprimer: 'Supprimer',
      annuler: 'Annuler',
      aucunMedicament: 'Aucun médicament trouvé',
      supprimerMedicament: 'Supprimer le médicament',
      confirmSupprimer: 'Voulez-vous vraiment supprimer ?',
      medicamentSupprime: 'Médicament supprimé avec succès !',
      page: 'Page',
      nom: 'Nom',
      telephone: 'Téléphone',
      email: 'Email',
      dateNaissance: 'Date de naissance',
      actions: 'Actions',
      aucunClient: 'Aucun client trouvé',
      rechercherClient: '🔍 Rechercher un client...',
      rechercherFournisseur: '🔍 Rechercher un fournisseur...',
      aucunFournisseur: 'Aucun fournisseur trouvé',
      confirmerSuppression: 'Voulez-vous vraiment supprimer ?',
      rechercheGlobale: 'Recherche Globale',
      rechercherPlaceholder: 'Rechercher médicaments, clients, fournisseurs, ventes...',
      resultats: 'résultat(s) pour',
      aucunResultat: 'Aucun résultat pour',
      essayerAutres: "Essayez avec d'autres mots-clés",
      minCaracteres: 'Entrez au moins 2 caractères pour rechercher...',
      suggestions: 'Suggestions de recherche',
      parametresCompte: 'Paramètres du compte',
      modifierEmail: "Modifier l'adresse email",
      actuel: 'Actuel',
      nonDefini: 'Non défini',
      nouvelEmail: 'Nouvel email',
      emailRequis: 'Email requis',
      formatInvalide: 'Format invalide',
      enregistrer: 'Enregistrer',
      modifierMotDePasse: 'Modifier le mot de passe',
      nouveauMotDePasse: 'Nouveau mot de passe',
      minimum6: 'Minimum 6 caractères',
      minimum6Requis: 'Minimum 6 caractères requis',
      confirmerMotDePasse: 'Confirmer le mot de passe',
      repeterMotDePasse: 'Répéter le mot de passe',
      motDePasseNonCorrespondant: 'Les mots de passe ne correspondent pas',
      emailMisAJour: 'Email mis à jour avec succès',
      motDePasseMisAJour: 'Mot de passe mis à jour',
      erreurMiseAJour: 'Erreur lors de la mise à jour',
      fermer: 'Fermer',
      date: 'Date',
      articles: 'Articles',
      total: 'Total',
      ordonnance: 'Ordonnance',
      articleS: 'article(s)',
      aucuneVente: 'Aucune vente enregistrée',
      supprimerVente: 'Supprimer la vente',
      confirmSupprimerVente: 'Voulez-vous vraiment supprimer cette vente ?',
      venteSupprimee: 'Vente supprimée avec succès !',
      medicament: 'Médicament',
      nouveau: 'Nouveau',
      retour: 'Retour',
      nomObligatoire: 'Le nom est obligatoire',
      reference: 'Référence',
      referenceObligatoire: 'La référence est obligatoire',
      choisirCategorie: 'Choisir une catégorie...',
      categorieObligatoire: 'La catégorie est obligatoire',
      choisirFournisseur: 'Choisir un fournisseur...',
      fournisseurObligatoire: 'Le fournisseur est obligatoire',
      prixInvalide: 'Prix invalide (minimum 0)',
      quantiteStock: 'Quantité en stock',
      quantiteInvalide: 'Quantité invalide',
      seuilAlerte: "Seuil d'alerte",
      dateObligatoire: 'La date est obligatoire',
      description: 'Description',
      descriptionPlaceholder: 'Description du médicament...',
      ordonnanceMedicale: 'Ordonnance médicale requise',
      medicamentModifie: 'Médicament modifié avec succès !',
      medicamentAjoute: 'Médicament ajouté avec succès !',
      fournisseur: 'Fournisseur',
      nomFournisseur: 'Nom du fournisseur',
      telephoneObligatoire: 'Téléphone obligatoire',
      emailInvalide: 'Email invalide',
      ville: 'Ville',
      villePlaceholder: 'Ex: Casablanca',
      villeObligatoire: 'Ville obligatoire',
      adresse: 'Adresse complète',
      adressePlaceholder: 'Adresse complète',
      client: 'Client',
      nomComplet: 'Nom complet',
      nomPrenom: 'Nom et prénom',
      choisirClient: 'Choisir un client...',
      clientObligatoire: 'Client obligatoire',
      avecOrdonnance: 'Avec ordonnance médicale',
      medicamentsVendus: 'Médicaments vendus',
      choisirMedicament: 'Choisir médicament...',
      quantite: 'Qté',
      prixUnite: 'Prix/u',
      ajouterMedicament: 'Ajouter un médicament',
      enregistrerVente: 'Enregistrer la vente',
      imprimerOrdonnance: "Imprimer l'ordonnance",
      oui: 'Oui',
      non: 'Non',
      patient: 'Patient',
      medicamentsPrescrits: 'Médicaments prescrits',
      sousTotal: 'Sous-total',
      signaturePharmacien: 'Signature du pharmacien',
      cachetPharmacie: 'Cachet de la pharmacie',
      merciConfiance: 'Merci de votre confiance — PharmaGest © 2025',
      chargement: 'Chargement...',
      detailMedicament: 'Détail du Médicament',
    },
    ar: {
      dashboard: 'لوحة التحكم',
      tableauDeBord: 'لوحة التحكم',
      medicaments: 'الأدوية',
      fournisseurs: 'الموردون',
      clients: 'العملاء',
      ventes: 'المبيعات',
      recherche: 'البحث',
      rechercher: 'بحث',
      parametres: 'الإعدادات',
      modeSombre: 'الوضع الداكن',
      modeClaire: 'الوضع الفاتح',
      deconnexion: 'تسجيل الخروج',
      alertes: 'تنبيه مخزون',
      alertesStock: 'تنبيهات المخزون',
      expirentBientot: 'تنتهي قريباً',
      chiffreAffaires: 'رقم الأعمال',
      totalVentes: 'إجمالي المبيعات',
      ventesAujourdhui: 'مبيعات اليوم',
      actionsRapides: 'إجراءات سريعة',
      nouveauMedicament: '💊 دواء جديد',
      nouvelleVente: 'بيعة جديدة',
      nouveauClient: '👥 عميل جديد',
      nouveauFournisseur: '🏭 مورد جديد',
      top3: 'أكثر 3 أدوية مبيعاً',
      vendus: 'مباع',
      dernieresVentes: 'آخر المبيعات',
      mettreAJour: 'تحديث',
      expireLe: 'ينتهي في',
      unitesRestantes: 'وحدة متبقية',
      ajouter: 'إضافة',
      stockMedicaments: 'مخزون الأدوية',
      gererInventaire: 'إدارة مخزونك وتتبع تواريخ الانتهاء',
      nomReference: 'الاسم، المرجع...',
      categorie: 'الفئة',
      toutesCategories: 'كل الفئات',
      etatStock: 'حالة المخزون',
      tous: 'الكل',
      enAlerte: 'في تنبيه',
      prix: 'السعر',
      stock: 'المخزون',
      expiration: 'تاريخ الانتهاء',
      unites: 'وحدات',
      ordonnanceRequise: 'وصفة طبية مطلوبة',
      voirDetails: 'عرض التفاصيل',
      modifier: 'تعديل',
      supprimer: 'حذف',
      annuler: 'إلغاء',
      aucunMedicament: 'لا يوجد دواء',
      supprimerMedicament: 'حذف الدواء',
      confirmSupprimer: 'هل تريد حذف هذا الدواء؟',
      medicamentSupprime: 'تم حذف الدواء بنجاح!',
      page: 'صفحة',
      nom: 'الاسم',
      telephone: 'الهاتف',
      email: 'البريد الإلكتروني',
      dateNaissance: 'تاريخ الميلاد',
      actions: 'الإجراءات',
      aucunClient: 'لا يوجد عميل',
      rechercherClient: '🔍 البحث عن عميل...',
      rechercherFournisseur: '🔍 البحث عن مورد...',
      aucunFournisseur: 'لا يوجد مورد',
      confirmerSuppression: 'هل تريد الحذف؟',
      rechercheGlobale: 'بحث شامل',
      rechercherPlaceholder: 'البحث عن أدوية، عملاء، موردين، مبيعات...',
      resultats: 'نتيجة (نتائج) لـ',
      aucunResultat: 'لا توجد نتائج لـ',
      essayerAutres: 'جرب كلمات مفتاحية أخرى',
      minCaracteres: 'أدخل حرفين على الأقل للبحث...',
      suggestions: 'اقتراحات البحث',
      parametresCompte: 'إعدادات الحساب',
      modifierEmail: 'تعديل البريد الإلكتروني',
      actuel: 'الحالي',
      nonDefini: 'غير محدد',
      nouvelEmail: 'البريد الجديد',
      emailRequis: 'البريد الإلكتروني مطلوب',
      formatInvalide: 'صيغة غير صحيحة',
      enregistrer: 'حفظ',
      modifierMotDePasse: 'تعديل كلمة المرور',
      nouveauMotDePasse: 'كلمة المرور الجديدة',
      minimum6: 'على الأقل 6 أحرف',
      minimum6Requis: '6 أحرف على الأقل مطلوبة',
      confirmerMotDePasse: 'تأكيد كلمة المرور',
      repeterMotDePasse: 'أعد كتابة كلمة المرور',
      motDePasseNonCorrespondant: 'كلمتا المرور غير متطابقتين',
      emailMisAJour: 'تم تحديث البريد الإلكتروني بنجاح',
      motDePasseMisAJour: 'تم تحديث كلمة المرور',
      erreurMiseAJour: 'خطأ أثناء التحديث',
      fermer: 'إغلاق',
      date: 'التاريخ',
      articles: 'المنتجات',
      total: 'المجموع',
      ordonnance: 'وصفة طبية',
      articleS: 'منتج(ات)',
      aucuneVente: 'لا توجد مبيعات مسجلة',
      supprimerVente: 'حذف البيعة',
      confirmSupprimerVente: 'هل تريد حذف هذه البيعة؟',
      venteSupprimee: 'تم حذف البيعة بنجاح!',
      medicament: 'دواء',
      nouveau: 'جديد',
      retour: 'رجوع',
      nomObligatoire: 'الاسم مطلوب',
      reference: 'المرجع',
      referenceObligatoire: 'المرجع مطلوب',
      choisirCategorie: 'اختر فئة...',
      categorieObligatoire: 'الفئة مطلوبة',
      choisirFournisseur: 'اختر موردًا...',
      fournisseurObligatoire: 'المورد مطلوب',
      prixInvalide: 'سعر غير صحيح (الحد الأدنى 0)',
      quantiteStock: 'الكمية في المخزون',
      quantiteInvalide: 'كمية غير صحيحة',
      seuilAlerte: 'حد التنبيه',
      dateObligatoire: 'التاريخ مطلوب',
      description: 'الوصف',
      descriptionPlaceholder: 'وصف الدواء...',
      ordonnanceMedicale: 'وصفة طبية مطلوبة',
      medicamentModifie: 'تم تعديل الدواء بنجاح!',
      medicamentAjoute: 'تم إضافة الدواء بنجاح!',
      fournisseur: 'مورد',
      nomFournisseur: 'اسم المورد',
      telephoneObligatoire: 'الهاتف مطلوب',
      emailInvalide: 'البريد الإلكتروني غير صحيح',
      ville: 'المدينة',
      villePlaceholder: 'مثال: الدار البيضاء',
      villeObligatoire: 'المدينة مطلوبة',
      adresse: 'العنوان الكامل',
      adressePlaceholder: 'العنوان الكامل',
      client: 'عميل',
      nomComplet: 'الاسم الكامل',
      nomPrenom: 'الاسم والنسب',
      choisirClient: 'اختر عميلاً...',
      clientObligatoire: 'العميل مطلوب',
      avecOrdonnance: 'مع وصفة طبية',
      medicamentsVendus: 'الأدوية المباعة',
      choisirMedicament: 'اختر دواءً...',
      quantite: 'الكمية',
      prixUnite: 'السعر/وحدة',
      ajouterMedicament: 'إضافة دواء',
      enregistrerVente: 'تسجيل البيعة',
      imprimerOrdonnance: 'طباعة الوصفة',
      oui: 'نعم',
      non: 'لا',
      patient: 'المريض',
      medicamentsPrescrits: 'الأدوية الموصوفة',
      sousTotal: 'المجموع الجزئي',
      signaturePharmacien: 'توقيع الصيدلاني',
      cachetPharmacie: 'ختم الصيدلية',
      merciConfiance: 'شكراً لثقتكم — PharmaGest © 2025',
      chargement: 'جارٍ التحميل...',
      detailMedicament: 'تفاصيل الدواء',
    },
    en: {
      dashboard: 'Dashboard',
      tableauDeBord: 'Dashboard',
      medicaments: 'Medicines',
      fournisseurs: 'Suppliers',
      clients: 'Clients',
      ventes: 'Sales',
      recherche: 'Search',
      rechercher: 'Search',
      parametres: 'Settings',
      modeSombre: 'Dark mode',
      modeClaire: 'Light mode',
      deconnexion: 'Logout',
      alertes: 'stock alert(s)',
      alertesStock: 'Stock Alerts',
      expirentBientot: 'Expiring soon',
      chiffreAffaires: 'Revenue',
      totalVentes: 'Total sales',
      ventesAujourdhui: "Today's sales",
      actionsRapides: 'Quick actions',
      nouveauMedicament: '💊 New medicine',
      nouvelleVente: 'New sale',
      nouveauClient: '👥 New client',
      nouveauFournisseur: '🏭 New supplier',
      top3: 'Top 3 best-selling medicines',
      vendus: 'sold',
      dernieresVentes: 'Latest sales',
      mettreAJour: 'Update',
      expireLe: 'Expires on',
      unitesRestantes: 'units remaining',
      ajouter: 'Add',
      stockMedicaments: 'Medicine Stock',
      gererInventaire: 'Manage your inventory',
      nomReference: 'Name, reference...',
      categorie: 'Category',
      toutesCategories: 'All categories',
      etatStock: 'Stock Status',
      tous: 'All',
      enAlerte: 'On alert',
      prix: 'Price',
      stock: 'Stock',
      expiration: 'Expiration',
      unites: 'units',
      ordonnanceRequise: 'Prescription required',
      voirDetails: 'View details',
      modifier: 'Edit',
      supprimer: 'Delete',
      annuler: 'Cancel',
      aucunMedicament: 'No medicine found',
      supprimerMedicament: 'Delete medicine',
      confirmSupprimer: 'Are you sure you want to delete?',
      medicamentSupprime: 'Medicine deleted successfully!',
      page: 'Page',
      nom: 'Name',
      telephone: 'Phone',
      email: 'Email',
      dateNaissance: 'Date of birth',
      actions: 'Actions',
      aucunClient: 'No client found',
      rechercherClient: '🔍 Search for a client...',
      rechercherFournisseur: '🔍 Search for a supplier...',
      aucunFournisseur: 'No supplier found',
      confirmerSuppression: 'Are you sure you want to delete?',
      rechercheGlobale: 'Global Search',
      rechercherPlaceholder: 'Search medicines, clients, suppliers, sales...',
      resultats: 'result(s) for',
      aucunResultat: 'No results for',
      essayerAutres: 'Try other keywords',
      minCaracteres: 'Enter at least 2 characters to search...',
      suggestions: 'Search suggestions',
      parametresCompte: 'Account Settings',
      modifierEmail: 'Modify email address',
      actuel: 'Current',
      nonDefini: 'Not defined',
      nouvelEmail: 'New email',
      emailRequis: 'Email required',
      formatInvalide: 'Invalid format',
      enregistrer: 'Save',
      modifierMotDePasse: 'Change password',
      nouveauMotDePasse: 'New password',
      minimum6: 'Minimum 6 characters',
      minimum6Requis: 'Minimum 6 characters required',
      confirmerMotDePasse: 'Confirm password',
      repeterMotDePasse: 'Repeat password',
      motDePasseNonCorrespondant: 'Passwords do not match',
      emailMisAJour: 'Email updated successfully',
      motDePasseMisAJour: 'Password updated successfully',
      erreurMiseAJour: 'Error during update',
      fermer: 'Close',
      date: 'Date',
      articles: 'Items',
      total: 'Total',
      ordonnance: 'Prescription',
      articleS: 'item(s)',
      aucuneVente: 'No sales recorded',
      supprimerVente: 'Delete sale',
      confirmSupprimerVente: 'Are you sure you want to delete this sale?',
      venteSupprimee: 'Sale deleted successfully!',
      medicament: 'Medicine',
      nouveau: 'New',
      retour: 'Back',
      nomObligatoire: 'Name is required',
      reference: 'Reference',
      referenceObligatoire: 'Reference is required',
      choisirCategorie: 'Choose a category...',
      categorieObligatoire: 'Category is required',
      choisirFournisseur: 'Choose a supplier...',
      fournisseurObligatoire: 'Supplier is required',
      prixInvalide: 'Invalid price (minimum 0)',
      quantiteStock: 'Stock quantity',
      quantiteInvalide: 'Invalid quantity',
      seuilAlerte: 'Alert threshold',
      dateObligatoire: 'Date is required',
      description: 'Description',
      descriptionPlaceholder: 'Medicine description...',
      ordonnanceMedicale: 'Medical prescription required',
      medicamentModifie: 'Medicine updated successfully!',
      medicamentAjoute: 'Medicine added successfully!',
      fournisseur: 'Supplier',
      nomFournisseur: 'Supplier name',
      telephoneObligatoire: 'Phone is required',
      emailInvalide: 'Invalid email',
      ville: 'City',
      villePlaceholder: 'Ex: Casablanca',
      villeObligatoire: 'City is required',
      adresse: 'Full address',
      adressePlaceholder: 'Full address',
      client: 'Client',
      nomComplet: 'Full name',
      nomPrenom: 'First and last name',
      choisirClient: 'Choose a client...',
      clientObligatoire: 'Client is required',
      avecOrdonnance: 'With medical prescription',
      medicamentsVendus: 'Sold medicines',
      choisirMedicament: 'Choose medicine...',
      quantite: 'Qty',
      prixUnite: 'Price/unit',
      ajouterMedicament: 'Add medicine',
      enregistrerVente: 'Save sale',
      imprimerOrdonnance: 'Print prescription',
      oui: 'Yes',
      non: 'No',
      patient: 'Patient',
      medicamentsPrescrits: 'Prescribed medicines',
      sousTotal: 'Subtotal',
      signaturePharmacien: 'Pharmacist signature',
      cachetPharmacie: 'Pharmacy stamp',
      merciConfiance: 'Thank you for your trust — PharmaGest © 2025',
      chargement: 'Loading...',
      detailMedicament: 'Medicine Detail',
    }
  };

  constructor() {
    const saved = localStorage.getItem('langue') as Langue;
    if (saved) this.setLangue(saved);
  }

  t = computed(() => this.traductions[this.langue()]);

  setLangue(lang: Langue): void {
    this.langue.set(lang);
    localStorage.setItem('langue', lang);
    if (lang === 'ar') {
      document.documentElement.setAttribute('dir', 'rtl');
    } else {
      document.documentElement.setAttribute('dir', 'ltr');
    }
  }

  toggle(): void {
    const ordre: Langue[] = ['fr', 'ar', 'en'];
    const index = ordre.indexOf(this.langue());
    this.setLangue(ordre[(index + 1) % 3]);
  }
}